config/routes.rb
Rails.application.routes.draw do
  get 'traders/show'
  get 'personals/show'
  devise_for :personals, controllers:{
    sessions:      'personals/sessions',
    passwords:     'personals/passwords',
    registrations: 'personals/registrations'
  }
  devise_for :traders, controllers:{
    sessions:      'traders/sessions',
    passwords:     'traders/passwords',
    registrations: 'traders/registrations'
  }
  devise_scope :personal do
    post 'personals/guest_sign_in', to: 'personals/sessions#new_guest'
  end
  devise_scope :trader do
    post 'traders/guest_sign_in', to: 'traders/sessions#new_guest'
  end

  root to: 'cats#index'
  # resources :users, only: [:new, :create, :destroy]
  get 'cats/fortune'
  get 'cats/info'
  get 'cats/how_to_have'
  resources :cats do
    resources :comments, only: :create
    collection do
      get 'search' 
    end
    resource :favorites, only: [:create, :destroy]
    resources :families, only: [:index, :new, :create]
  end
  resources :traders, only: :show
  resources :personals, only: :show
end

app/models/trader.rb
class Trader < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.guest
    find_or_create_by(email: 'guest@example.com') do |trader|
      trader.password = SecureRandom.urlsafe_base64
      trader.password_confirmation = trader.password
      trader.t_name = 'ゲストユーザー(保護した方)'
      trader.t_postal_code = '111-1111'
      trader.area_id = '1'
      trader.t_city = '横浜市'
      trader.t_address_num = '下島町5丁目3ー３３'
      trader.t_tel = '01234567890'
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :families, dependent: :destroy
  has_many :cats, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to_active_hash :area

  with_options presence: true do
    validates :t_name
    validates :email
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, length: { minimum: 6 }
    validates :t_postal_code, format: { with: /\A\d{3}-\d{4}\z/ }
    validates :area_id, numericality: { other_than: 0 }
    validates :t_city
    validates :t_address_num
    validates :t_tel, format: { with: /\A\d{11}\z/ }
  end
end

app/controllers/traders/confirmations_controller.rb
# frozen_string_literal: true

class Traders::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/traders/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Traders::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/traders/passwords_controller.rb
# frozen_string_literal: true

class Traders::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/traders/registrations_controller.rb
# frozen_string_literal: true

class Traders::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create, :edit, :update, :destroy]
  before_action :check_guest, only: [:update, :destroy]
  before_action :redirect_root
  def check_guest
    redirect_to root_path, alert: 'ゲストユーザーの編集・削除はできません。' if resource.email == 'guest@example.com'
  end

  def redirect_root
    if personal_signed_in?
      redirect_to root_path
    end
  end
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:t_name, :t_postal_code, :area_id, :t_city, :t_address_num, :t_building_num, :t_tel])
  end

  #  更新（編集の反映）時にパスワード入力を省く
  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end

  #  更新後のパスを指定
  # def after_update_path_for(resource)
  #   trader_path(@trader.id)
  # end

  # def after_update_path_for(_resource)
  #   trader_path(id: current_trader.id)
  # end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/traders/sessions_controller.rb
#  frozen_string_literal: true

class Traders::SessionsController < Devise::SessionsController
  before_action :redirect_root
  def new_guest
    trader = Trader.guest
    sign_in trader
    redirect_to root_path, notice: 'ゲストユーザー（猫を保護した方）としてログインしました。'
  end

  def redirect_root
    if personal_signed_in?
      redirect_to root_path
    end 
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/traders/unlocks_controller.rb
# frozen_string_literal: true

class Traders::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
  before_action :redirect_root

  def show
    
  end

  private

  def redirect_root
    redirect_to root_path unless trader_signed_in? || personal_signed_in?
  end
end

app/helpers/traders_helper.rb
module TradersHelper
end

app/views/traders/show.html.erb
<%= render "shared/header" %>


<div class="mypage">
  <div class="my-page-in">
    <h2>マイページ</h2>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">登録名</th>
          <td class="detail-value"><%= current_trader.t_name %></td>
        </tr>
        <tr>
          <th class="detail-item">メールアドレス</th>
          <td class="detail-value"><%= current_trader.email %></td>
        </tr>
        <tr>
          <th class="detail-item">郵便番号</th>
          <td class="detail-value"><%= current_trader.t_postal_code %></td>
        </tr>
        <tr>
          <th class="detail-item">都道府県</th>
          <td class="detail-value"><%= current_trader.area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">市区長村</th>
          <td class="detail-value"><%= current_trader.t_city %></td>
        </tr>
        <tr>
          <th class="detail-item">番地</th>
          <td class="detail-value"><%= current_trader.t_address_num %></td>
        </tr>
        <tr>
          <th class="detail-item">建物名</th>
          <td class="detail-value"><%= current_trader.t_building_num %></td>
        </tr>
        <tr>
          <th class="detail-item">電話番号</th>
          <td class="detail-value"><%= current_trader.t_tel %></td>
        </tr>
      </tbody>
    </table>
    <%= link_to "マイページ情報の編集はこちら",edit_trader_registration_path %>

    <div class="contents-all-cat">
      <div class="contents">
        <div class="contents-name">
          <div class="trader-name-center">保護した猫一覧</div>
        </div>
      </div>
      <div class="contents_row">
        <% current_trader.cats.each do |cat| %>
          <div class="content_post" >
            <%= link_to cat_path(cat) do %>
              <div class="trader-one-cat">
              <% if cat.images.count > 0 %>
                <%= image_tag cat.images.first, class:'cat-image' %>
                <% if cat.family.present? %>
                  <div class='trader-family-done'>
                    <span>サポートを受けています</span>
                  </div>
                <% end %>
              <% end %>
              <div class="cat-name-center">
              <% if cat.sex_id == 1 %>
                <%= "#{cat.c_name}くん" %>
              <% elsif cat.sex_id == 2 %>
                <%= "#{cat.c_name}ちゃん" %>
              <% end %>
              </div>
              </div>
            <% end %> 
            <div class="choice"> 
            <%= link_to "編集", edit_cat_path(cat), class: "item-red-btn" %>
            <div class="choice-or">or</div>
            <%= link_to '削除', cat_path(cat), method: :delete, class:'item-destroy', data: { confirm: '本当に削除しますか？' } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to "戻る", :back, class:"link-login" %>
  </div>
</div>

<%= render "shared/footer"%>