config/routes.rb
Rails.application.routes.draw do
  get 'traders/show'
  get 'personals/show'
  devise_for :personals, controllers:{
    sessions:      'personals/sessions',
    passwords:     'personals/passwords',
    registrations: 'personals/registrations'
  }
  devise_for :traders, controllers:{
    sessions:      'traders/sessions',
    passwords:     'traders/passwords',
    registrations: 'traders/registrations'
  }
  devise_scope :personal do
    post 'personals/guest_sign_in', to: 'personals/sessions#new_guest'
  end
  devise_scope :trader do
    post 'traders/guest_sign_in', to: 'traders/sessions#new_guest'
  end

  root to: 'cats#index'
  # resources :users, only: [:new, :create, :destroy]
  get 'cats/fortune'
  get 'cats/info'
  get 'cats/how_to_have'
  resources :cats do
    resources :comments, only: :create
    collection do
      get 'search' 
    end
    resource :favorites, only: [:create, :destroy]
    resources :families, only: [:index, :new, :create]
  end
  resources :traders, only: :show
  resources :personals, only: :show
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :personal
  belongs_to :cat

  validates_uniqueness_of :cat_id, scope: :personal_id  # バリデーション（ユーザーと記事の組み合わせは一意）
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_cat
  before_action :authenticate_personal!

  def create
    @favorite = Favorite.new(personal_id: current_personal.id, cat_id: @cat.id)
    respond_to do |format|
      format.js if @favorite.save
    end
  end

  def destroy
    @favorite = Favorite.find_by(personal_id: current_personal.id, cat_id: @cat.id)
    respond_to do |format|
      format.js if @favorite.destroy
    end
  end

  private

  def set_cat
    @cat = Cat.find(params[:cat_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if personal_signed_in? %>
  <div id="favorite_<%= @cat.id %>" class="favorite-all">
    <% if Favorite.exists?(personal_id: current_personal.id, cat_id: @cat.id) %>
      <%= link_to cat_favorites_path(@cat), method: :delete, remote: true, class: "favorite-btn-delete" do %>
        <div class="fa-thumbs-down">
          <span> お気に入り登録済</span>
          <%= image_tag '137515.png', class:"icon-heart" %> <%= @cat.favorite.length %>
        </div>
      <% end %>
    <% else %>
      <%= link_to cat_favorites_path(@cat), method: :post, remote: true, class: "favorite-btn-create" do %>
        <div class="fa-thumbs-up">
          <span> お気に入り   登録</span>
          <%= image_tag '137515.png', class:"icon-heart" %> <%= @cat.favorite.length %>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class="fa-thumbs-up">
    <span> お気に入り登録数</span>
    ❤️<%= @cat.favorite.length %>
  </div>
<% end %>

app/views/favorites/create.js.erb
document.getElementById('favorite_<%= @cat.id %>').innerHTML = '<%= escape_javascript(render partial: 'favorites/favorite', locals: { cat: @cat }) %>'

app/views/favorites/destroy.js.erb
document.getElementById('favorite_<%= @cat.id %>').innerHTML = '<%= escape_javascript(render partial: 'favorites/favorite', locals: { cat: @cat }) %>'