config/routes.rb
Rails.application.routes.draw do
  get 'traders/show'
  get 'personals/show'
  devise_for :personals, controllers:{
    sessions:      'personals/sessions',
    passwords:     'personals/passwords',
    registrations: 'personals/registrations'
  }
  devise_for :traders, controllers:{
    sessions:      'traders/sessions',
    passwords:     'traders/passwords',
    registrations: 'traders/registrations'
  }
  devise_scope :personal do
    post 'personals/guest_sign_in', to: 'personals/sessions#new_guest'
  end
  devise_scope :trader do
    post 'traders/guest_sign_in', to: 'traders/sessions#new_guest'
  end

  root to: 'cats#index'
  # resources :users, only: [:new, :create, :destroy]
  get 'cats/fortune'
  get 'cats/info'
  get 'cats/how_to_have'
  resources :cats do
    resources :comments, only: :create
    collection do
      get 'search' 
    end
    resource :favorites, only: [:create, :destroy]
    resources :families, only: [:index, :new, :create]
  end
  resources :traders, only: :show
  resources :personals, only: :show
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <div>
    <% model.errors.full_messages.each do |message| %>
    <div class='error-message'>・<%= message %></div>
    <% end %>
  </div>
</div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert" id="alert">
    <a href="/" class="close" data-dismiss="alert"></a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p class="copyright">
    Copyright Cat-28730 2020.
  </p>
</footer>

app/views/shared/_header.html.erb
<%= render 'shared/flash_messages' %>

<header class="header">
  <div class="title">
    <div class="title-link">
      <%= link_to root_path do %>
      <div class="title-jump">
        <div class="title-name">Catmee</br>あなたにぴったりのネコに出会おう</div>
        <%= image_tag 'k0130_13 (1).png', class:"icon"%>
        <%= image_tag 'k0130_7.png', class:"icon"%>
      </div>
      <% end %>
    </div>

        <div class="trader-link">
        <% if personal_signed_in? %>
          <li ><%= link_to "マイページ", "/personals/#{current_personal.id}" %></li>
          <li ><%= link_to "ログアウト", destroy_personal_session_path, method: :delete %></li>
        <% elsif trader_signed_in? %>
          <li ><%= link_to "マイページ", "/traders/#{current_trader.id}"  %></li>
          <li> <%= link_to "ログアウト", destroy_trader_session_path, method: :delete %></li>
        <% else %>
          <li ><%= link_to "p新規登録", new_personal_registration_path %></li>
          <li ><%= link_to "pログイン", new_personal_session_path %></li>
          <li ><%= link_to "t新規登録", new_trader_registration_path %></li>
          <li><%= link_to "tログイン", new_trader_session_path %></li>
        <% end %>
        </div>  

  </div>


    <div class="user-menu">
    <ul >
      <li ><%= link_to "検索", search_cats_path, class:"favorite" %></li>
      <li ><%= link_to "ぴったり猫占い",  cats_fortune_path, class:"favorite" %></li>
      <% if trader_signed_in? %>
      <li ><%= link_to "猫登録", new_cat_path, class:"favorite" %></li>
      <% end %>
    </ul>
    <script>
    const button = document.getElementsByClassName("favorite");
      var buttons = Array.from(button);
      
      buttons.forEach(function(target){
        
        target.addEventListener('mouseover', function(){
          target.setAttribute("style", "background-color:royalblue; color:#ffff;");
        })
        target.addEventListener('mouseout', function(){
          target.removeAttribute("style", "background-color:royalblue; color:#ffff;");
        })
      });
    </script>


    <%# <ul class="header-bar-row">
    </ul> %>
    
    </div>


</header>