config/routes.rb
Rails.application.routes.draw do
  get 'traders/show'
  get 'personals/show'
  devise_for :personals, controllers:{
    sessions:      'personals/sessions',
    passwords:     'personals/passwords',
    registrations: 'personals/registrations'
  }
  devise_for :traders, controllers:{
    sessions:      'traders/sessions',
    passwords:     'traders/passwords',
    registrations: 'traders/registrations'
  }
  devise_scope :personal do
    post 'personals/guest_sign_in', to: 'personals/sessions#new_guest'
  end
  devise_scope :trader do
    post 'traders/guest_sign_in', to: 'traders/sessions#new_guest'
  end

  root to: 'cats#index'
  # resources :users, only: [:new, :create, :destroy]
  get 'cats/fortune'
  get 'cats/info'
  get 'cats/how_to_have'
  resources :cats do
    resources :comments, only: :create
    collection do
      get 'search' 
    end
    resource :favorites, only: [:create, :destroy]
    resources :families, only: [:index, :new, :create]
  end
  resources :traders, only: :show
  resources :personals, only: :show
end

app/models/cat.rb
class Cat < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :trader
  has_one :family, dependent: :destroy
  has_many_attached :images
  has_many :comments
  has_many :favorite, dependent: :destroy
  belongs_to_active_hash :breed
  belongs_to_active_hash :ope
  belongs_to_active_hash :sex
  belongs_to_active_hash :age
  belongs_to_active_hash :hair_length
  belongs_to_active_hash :color
  belongs_to_active_hash :how_many
  belongs_to_active_hash :eye_color
  belongs_to_active_hash :character
  belongs_to_active_hash :fleas
  belongs_to_active_hash :veccine
  belongs_to_active_hash :kuchu
  belongs_to_active_hash :single
  belongs_to_active_hash :senior

  validates :price, numericality: { greater_than_or_equal_to: 1000, less_than_or_equal_to: 9_999_999, allow_blank: true }

  validate :image_type, :image_size, :image_length

  with_options presence: true do
    validates :c_name, length: { maximum: 40 }
    validates :c_text, length: { maximum: 1000 }
    validates :ope_id
    validates :sex_id
    validates :age_id
    validates :character_id
    validates :fleas_id
    validates :veccine_id
    validates :kuchu_id
    validates :trader_id
    validates :images
  end

  with_options numericality: { other_than: 0 } do
    validates :ope_id
    validates :sex_id
    validates :age_id
    validates :character_id
    validates :fleas_id
    validates :veccine_id
    validates :kuchu_id
  end

  private

  def image_type
    images.each do |image|
      unless image.blob.content_type.in?(%('image/jpeg image/png'))
        image.purge
        errors.add(:images, 'はjpegまたはpng形式でアップロードしてください')
      end
    end
  end

  def image_size
    images.each do |image|
      if image.blob.byte_size > 5.megabytes
        image.purge
        errors.add(:images, 'は1つのファイル5MB以内にしてください')
      end
    end
  end

  def image_length
    return unless images.length > 5

    image.purge
    errors.add(:images, 'は5枚以内にしてください')
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :authenticate_trader!, except: [:index, :show, :search, :fortune, :info, :how_to_have]
  before_action :set_search, only: :search

  def index
    @cats = Cat.includes(:trader).order('created_at DESC').limit(30)
  end

  def show
    @cat = Cat.find(params[:id])
    @comment = Comment.new
    @comments = @cat.comments.includes(:personal, :trader)
  end

  def new
    @cats = Cat.new
  end

  def create
    @cats = Cat.new(cat_params)
    if @cats.valid?
      @cats.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.valid?
      @cat.update(cat_params)
      redirect_to cat_path
    else
      render 'edit'
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    if @cat.destroy
      redirect_to root_path
    else
      render 'show'
    end
  end

  def search
    @cats = Cat.includes(:trader).order('created_at DESC').limit(30)
    if @q = Cat.ransack(params[:q])
      @search_products = @q.result(distinct: true)
    end
  end

  private

  def cat_params
    params.require(:cat).permit(
      :c_name,
      :c_text,
      :price,
      :breed_id,
      :ope_id,
      :sex_id,
      :age_id,
      :hair_length_id,
      :color_id,
      :how_many_id,
      :eye_color_id,
      :character_id,
      :fleas_id,
      :veccine_id,
      :kuchu_id,
      :single_id,
      :senior_id,
      images: []
    ).merge(trader_id: current_trader.id)
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_index_swiper.html.erb
<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide family-top-base-pic">
      <img src="/assets/1.jpg"  width="700" height="450" >
      <%= link_to cats_info_path do%>
      <div class="family-top-base-info">
        <div class="family-top-info">初めて使う方へ</div>
        <div class="family-top-info2">使い方説明</div>
      </div>
      <% end %>
    </div>
    <div class="swiper-slide family-top-base-pic">
      <img src="/assets/2.jpg"  width="700" height="450" >
      <%= link_to cats_how_to_have_path do%>
      <div class="family-top-base-info">
        <div class="family-top-info">猫と暮らそう</div>
        <div class="family-top-info2">猫の飼い方</div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="swiper-pagination"></div>
</div>

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

app/views/cats/fortune.html.erb
<%= render "shared/header" %>

<div class="contents-show">
  <div class="content">
    <h3>ぴったり猫占い</h3>
    <div class="content-all">
    現在メンテナンス中です。
    </div>
    <%= link_to "戻る", root_path, class:"link-login" %>
  </div>
</div>

<%= render "shared/footer"%>

app/views/cats/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <%# <div class="family-top-base" id="info"> 
    <div class="family-top-base-pic" >  
      <img src="/assets/1.jpg"  width="700" height="450" >
      <div class="family-top-base-info">
        <div class="family-top-info">初めて使う方へ</div>
        <div class="family-top-info2">使い方説明</div>
      </div>
      <div class="family-top-base-buttun">
        <input type="button" value="◀︎" onclick="go_back()" class="mypic-arrow" >
        <input type="button" value="▶︎" onclick="go_forward()" class="mypic-arrow" >
      </div>
    </div>
  </div> %>

<%= render "cats/index_swiper" %>

  <%# <div class="movie">
  <p>本日の猫ちゃん  毎日6：00動画更新中</p>
    <div class="video_flame">

<iframe width="560" height="315" src="https://www.youtube.com/embed/_qtJGuORO_k?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    
    </div>
  </div> %>
  <div class="contents-all">
    <div class="contents">
      <div class="contents-name">
        <div class="contents-name-center">猫一覧</div>
      </div>
    <div class="contents_row">
      <% @cats.each do |cat| %>
        <div class="content_post">
        <%= link_to cat_path(cat) do %>
          <div class="one_cat">
          <% if cat.images.count > 0 %>
            <%= image_tag cat.images.first, class:'cat-image' %>
              <% if personal_signed_in? && Family.exists?(personal_id: current_personal.id, cat_id: cat.id)  %>
              <div class='family-done'>
                  <span>サポートしています</span>
              </div>
              <% end  %>
              <% if personal_signed_in? && Favorite.exists?(personal_id: current_personal.id, cat_id: cat.id) %>
                <div class="favorite-mark">
                <%= image_tag '137515.png', class:"icon-heart" %>
                </div>
              <% end %>
          <% end %>
          <div class="cat-name-center">
          <% if cat.sex_id == 1 %>
            <%= "#{cat.c_name}くん" %>
          <% elsif cat.sex_id == 2 %>
            <%= "#{cat.c_name}ちゃん" %>
          <% end %>
          </div>
          </div>
        <% end %>  
        </div>
      <% end %>
    </div>
    </div>
  </div>
 
</div>

<%= render "shared/footer"%>

app/views/cats/new.html.erb
<%= render "shared/header" %>

<div class="contents-show">
  <div class="content">
    <h3>猫を登録する</h3>
    <div class="content-all">
    <%= form_with model: @cats, url: cats_path, method: :post, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <div class="list">
        <div class="list-in">個体名
          <span class="indispensable">必須</span>
        </div>
          <div class="list-1">
          <%= f.text_field :c_name, placeholder: "猫の名前（40字以内）", maxlength:"40" %>
          </div>
      </div>
      <div class="lists">
        <div class="list-in">写真
          <span class="indispensable">必須</span>
            <div class="click-upload">
              <p>
                クリックしてファイルをアップロード
              </p>
            </div>
        </div>
        <div class="center-center">
          <div class="cat-image-smaller">
            <%= f.file_field :images, name: 'cat[images][]', id: 'cat_image', placeholder: "Image Url",multipul: true %>
          </div>
          <div id="image-list" class="cat-image-small"></div>
        </div>
      </div>
      <div class="list">
        <div class="list-in">性格
          <span class="indispensable">必須</span>
        </div>
          <div class="list-2">
          <%= f.collection_select :character_id, Character.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">紹介文
          <span class="indispensable">必須</span>
        </div>
          <div >
          <%= f.text_area :c_text, placeholder: "紹介文（1000字以内）",class:"list-3", maxlength: "1000", wrap:"hard" %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">性別
          <span class="indispensable">必須</span>
        </div>
          <div class="list-4">
          <%= f.collection_select :sex_id, Sex.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">避妊去勢手術
          <span class="indispensable">必須</span>
        </div>
          <div class="list-5">
          <%= f.collection_select :ope_id, Ope.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">年齢
          <span class="indispensable">必須</span>
        </div>
          <div class="list-6">
          <%= f.collection_select :age_id, Age.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">ノミ取り処置
          <span class="indispensable">必須</span>
        </div> 
          <div class="list-7">
          <%= f.collection_select :fleas_id, Fleas.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">ワクチン処置
        <span class="indispensable">必須</span>
        </div>
          <div class="list-8">
          <%= f.collection_select :veccine_id, Veccine.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">駆虫処置
          <span class="indispensable">必須</span>
        </div>
          <div class="list-9">
          <%= f.collection_select :kuchu_id, Kuchu.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">保護にかかった金額
        </div>
          <div class="list-10">
          <%= f.text_field :price, placeholder: "1000円以上でご入力ください" %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">種類
        </div>
          <div class="list-11">
          <%= f.collection_select :breed_id, Breed.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">毛の長さ
        </div>
          <div class="list-12">
          <%= f.collection_select :hair_length_id, HairLength.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">毛の色
        </div>
          <div class="list-13">
          <%= f.collection_select :color_id, Color.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">眼の色
        </div>
          <div class="list-14">
            <%= f.collection_select :eye_color_id, EyeColor.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
      <div class="list-in">希望飼育頭数
        </div>
          <div class="list-15">
          <%= f.collection_select :how_many_id, HowMany.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">独身者
        </div>
          <div class="list-16">
            <%= f.collection_select :single_id, Single.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">高齢者
        </div>
          <div class="list-17">
            <%= f.collection_select :senior_id, Senior.all, :id, :name, {} %>
          </div>
      </div>
      <div class="list-center">
        <div class="list-18">
        <%= f.submit "登録する" %>
        </div>
      </div>
    <% end %>
    <%= link_to "戻る", :back, class:"link-login" %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/cats/search.html.erb
<%= render "shared/header" %>

<div class="contents-show">
  <div class="content">
    <h3>猫を検索する</h3>
    <div class="content-all-search">
    <%= search_form_for(@q, url: search_cats_path, local:true)do |f| %>
      <div class="list">
        <div class="list-in">名前検索
        </div>
          <div class="list-1">
          <%= f.search_field :c_name_cont, placeholder: "猫の名前を入力", maxlength:"40" %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">性格
        </div>
          <div class="list-2">
          <%= f.collection_select :character_id_eq, @character, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">性別
        </div>
          <div class="list-s4">
          <%= f.collection_select :sex_id_eq, @sex, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">去勢避妊手術
        </div>
          <div class="list-s5">
          <%= f.collection_select :ope_id_eq, @ope, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">年齢
        </div>
          <div class="list-s6">
          <%= f.collection_select :age_id_eq, @age, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">ノミ取り処置
        </div> 
          <div class="list-s7">
          <%= f.collection_select :fleas_id_eq, @fleas, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">ワクチン処置
        </div>
          <div class="list-s8">
          <%= f.collection_select :veccine_id_eq, @veccine, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">駆虫処置
        </div>
          <div class="list-s9">
          <%= f.collection_select :kuchu_id_eq, @kuchu, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">保護にかかった金額
        </div>
          <div class="list-s10">
          <%= f.number_field :price_gteq %>円以上
          <%= f.number_field :price_lt %>円未満
          </div>
      </div>
      <div class="list">
        <div class="list-in">種類
        </div>
          <div class="list-s11">
          <%= f.collection_select :breed_id_eq, @breed, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">毛の長さ
        </div>
          <div class="list-s12">
          <%= f.collection_select :hair_length_id_eq, @hair_length, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">毛の色
        </div>
          <div class="list-s13">
          <%= f.collection_select :color_id_eq, @color, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">目の色
        </div>
          <div class="list-s14">
            <%= f.collection_select :eye_color_id_eq, @eye_color, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
      <div class="list-in">希望飼育頭数
        </div>
          <div class="list-s15">
          <%= f.collection_select :how_many_id_eq, @how_many, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">独身者
        </div>
          <div class="list-s16">
            <%= f.collection_select :single_id_eq, @single, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list">
        <div class="list-in">高齢者
        </div>
          <div class="list-s17">
            <%= f.collection_select :senior_id_eq, @senior, :id, :name, disabled: 0, :include_blank => '指定なし' %>
          </div>
      </div>
      <div class="list-centers">
        <div class="list-18">
        <%= f.submit "検索する" %>
        </div>
        <div class="list-19">
        <%= link_to "クリア", search_cats_path %>
        </div>
      </div>
    <% end %>
    </div>

   <div class="contents-all-cat">
      <div class="contents-search">
        <div class="contents-name">
          <div class="trader-name-center">検索結果一覧</div>
        </div>
      </div>
      <div class="contents_row">
      <% @cats.each do |cat| %>
      <% @search_products.each do |search_product| %>
      <% if search_product == cat %>  
          <div class="content_post" >
            <%= link_to cat_path(cat) do %>
              <div class="trader-one-cat">
                <% if cat.images.count > 0 %>
                  <%= image_tag cat.images.first, class:'cat-image' %>
                    <% if personal_signed_in? && Family.exists?(personal_id: current_personal.id, cat_id: cat.id)  %>
                    <div class='family-done'>
                        <span>サポートしています</span>
                    </div>
                    <% end  %>
                    <% if personal_signed_in? && Favorite.exists?(personal_id: current_personal.id, cat_id: cat.id) %>
                      <div class="favorite-mark">
                      <%= image_tag '137515.png', class:"icon-heart" %>
                      </div>
                    <% end %>
                    
                <% end %>
                    <div class="cat-name-center">
                    <% if cat.sex_id == 1 %>
                      <%= "#{cat.c_name}くん" %>
                    <% elsif cat.sex_id == 2 %>
                      <%= "#{cat.c_name}ちゃん" %>
                    <% end %>
                    </div>
              </div>
            <% end %> 
          </div>
      <% end %>
      <% end %>
      <% end %>
      </div>
    </div>
    <%= link_to "戻る", root_path, class:"link-login" %>
  </div>
</div>

<%= render "shared/footer"%>

app/views/cats/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <div class='show-one-cat'>
      <div class="show-cat-scroll">
        <% @cat.images.each do |img| %>
          <%= image_tag(img, class: "show-cat-image") %>
        <% end %>
      </div>
      <div class="show-pictures">
      <div class="show-cat-pictures">
        <% @cat.images.each do |img| %>
          <p><%= image_tag(img, class: "show-cat-images") %></p>
        <% end %>
      </div>
      </div>
      <div class="btn">
      <% if trader_signed_in? && current_trader.id == @cat.trader_id %>
        <%= link_to '編集', edit_cat_path, method: :get, class: "item-red-btn" %>
        <p class='or-text'>or</p>
        <%= link_to '削除', cat_path, method: :delete, class:'item-destroy', data: { confirm: '本当に削除しますか？' } %>
      <% else %>
            <%= link_to "サポーターになる",  cat_families_path(@cat.id), class:"item-blue-btn" %>
            <% if personal_signed_in? && Family.exists?(personal_id: current_personal.id, cat_id: @cat.id)  %>
              <div class="fa-thumbs-suport">
                  <span>あなたはこの子を</br>サポートしています</span>
              </div>
            <% end  %>
      <% end %>
      </div>


      <h2 class="name">
        <% if @cat.sex_id == 1 %>
          <%= "#{@cat.c_name}くん" %>
        <% elsif @cat.sex_id == 2 %>
          <%= "#{@cat.c_name}ちゃん" %>
        <% end %>
      </h2>

      <%= render "favorites/favorite", cat: @cat %>

      <div class="table-twin">
        <table class="detail-table">
          <tbody>
            <tr>
              <th class="detail-item">性格</th>
              <td class="detail-value"><%= @cat.character.name %></td>
            </tr>
            <tr>
              <th class="detail-item">年齢</th>
              <td class="detail-value"><%= @cat.age.name %></td>
            </tr>
            <tr>
              <th class="detail-item">性別</th>
              <td class="detail-value"><%= @cat.sex.name %></td>
            </tr>
            <tr>
              <th class="detail-item">去勢・避妊手術</th>
              <td class="detail-value"><%= @cat.ope.name %></td>
            </tr>
            <tr>
              <th class="detail-item">種類</th>
              <td class="detail-value"><%= @cat.breed.name %></td>
            </tr>
            <tr>
              <th class="detail-item">毛の長さ</th>
              <td class="detail-value"><%= @cat.hair_length.name %></td>
            </tr>
            <tr>
              <th class="detail-item">毛の色</th>
              <td class="detail-value"><%= @cat.color.name %></td>
            </tr>
            <tr>
              <th class="detail-item">眼の色</th>
              <td class="detail-value"><%= @cat.eye_color.name %></td>
            </tr>
         </tbody>
        </table>
        <table class="detail-table">
          <tbody>
            <tr>
              <th class="detail-item">希望飼育頭数</th>
              <td class="detail-value"><%= @cat.how_many.name %></td>
            </tr>
            <tr>
              <th class="detail-item">独身者応募</th>
              <td class="detail-value"><%= @cat.single.name %></td>
            </tr>
            <tr>
              <th class="detail-item">高齢者応募</th>
              <td class="detail-value"><%= @cat.senior.name %></td>
            </tr>
            <tr>
              <th class="detail-item">保護している団体や個人様</th>
              <td class="detail-value"><%= @cat.trader.t_name %></td>
            </tr> 
            <tr>
              <th class="detail-item">ノミ取り処置</th>
              <td class="detail-value"><%= @cat.fleas.name %></td>
            </tr>
            <tr>
              <th class="detail-item">ワクチン処置</th>
              <td class="detail-value"><%= @cat.veccine.name %></td>
            </tr>
            <tr>
              <th class="detail-item">駆虫処置</th>
              <td class="detail-value"><%= @cat.kuchu.name %></td>
            </tr>
            <tr>
              <th class="detail-item">保護にかかった金額</th>
              <td class="detail-value"><%= "#{@cat.price}円(税込)"%></td>
            </tr>
          </tbody>
        </table>
      </div>
        <table class="detail-table-under">
          <tbody>
            <tr>
              <th class="detail-item-under">保護された方からのメッセージ</th>
            </tr>
            <tr>
              <td class="detail-value-under" maxlength="1000" ><%= @cat.c_text %> </td>
            </tr>
          </tbody>
        </table>

        <div class="comment-container">
          <div class="comment-center">
          <% if trader_signed_in? or personal_signed_in? %>
            <%= form_with(model: [@cat, @comment], local: true) do |f| %>
              <%= f.text_area :comment, placeholder: "コメントする(300文字以内)", maxlength: "300", class:"comment-form", wrap:"hard" %>
              <%= f.submit "コメント投稿", class:"item-blue-btn" %>
            <% end %>
          <% else %>
            <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
          <% end %>
          </div>
          <div class="comments">
            <h4>＜コメント一覧＞</h4>
            <div class="comment-scroll">
            <% if @comments.present? %>
              <% @comments.each do |comment| %>
                <p>
                <% if comment.personal_id.present? %>
                      <strong><%= comment.personal.nickname %>：</strong>
                <% else %>
                      <strong><%= comment.trader.t_name %>：</strong>
                <% end %>
                  <%= comment.comment %>
                </p>
              <% end %>
            <% end %>
            </div>
        </div>

      </div>
    <%= link_to "戻る", root_path, class:"link-login" %>
    </div>
  </div>
</div>
  <%# /商品の概要 %>

<%= render "shared/footer"%>